# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Setup Android SDK Tools
      # uses: android-actions/setup-android@72fdd2e74f58fb338a2743720c0847b8becf1589
      uses: android-actions/setup-android@v2.0.2
    - name: list some files
      run: ls $ANDROID_SDK_ROOT/platforms
    - name: Build with Ant
      run: ant compile_for_android -f build/build.xml
